### ISSUE TITLE
是正処置管理SYS

### ISSUE THREAD

**Issue by jms-funato** [jms-web/FMS#285]
### 概要
- 既存SYSで扱えないタイプの不適合を管理するシステム
- 是正処置要求書(発生)と是正処置要求書(流出)の2つのデータを管理する(レポートレベルでほぼ一緒)
- (発生)登録時は(流出)もセットで登録が必要
- 機能ベースはNCR-CARに近い
- NCRほどステージフローパターンはなくほぼ一本道
- 登録内容の集計・分析も行いたいとのことだったが、件数が年間30~40件程度であり、社外要因も多いため、共通項はあまりないそうなので、集計機能は一旦保留とする

### 仕様
- 発行番号(報告書番号)は、別書類である苦情受付票に記載のNoを手入力する
フォーマット：G20210000　先頭のアルファベットは部門から取得 業管=Gなど
- (流出)のみ登録する場合もあるため、新規登録ボタンは(流出)と(報告)両方用意する
- 各メール通知は担当者+その上長へ送信
- ST1担当者は部・課を選択して担当者一覧から選択する
- レポートには表示しないが、プログラム画面上の各ステージにフリースペース(自由記入)欄を用意する
この項目は当該システムの担当者以外に、課長等の管理者層ユーザーにも編集権限を持たせる

### 確認事項
- [x] レポート出力の元となるExcelファイルをいただく
- [x] 各ステージ担当者の一覧を作成いただく　対象業務グループ一覧 or 担当者一覧(マスタ)
- [x] (発生)と(流出)の発行番号は一緒？
- [x] プロセスオーナーは誰を指している？
起草者？ or ST1で登録する責任者?
→資料中記載の特定の担当者
`\\sv18\zensha\１一般作業フォルダ\⑱事務改善専門部会活動\JMS作業フォルダ\604提出是正処置の改善システム化.xlsx`
- [x] 是正処置での部門は複合材・航空機・LPだけでよい？
※担当者の中に業務管理部も含まれている
→部門は航空機・複合材・業務管理　LPは不要
- [x] 是正処置流出のST2の担当者
担当者がパートかどうかの識別方法？
→社員区分：フジワラ or テクノ

### 7/28 レビュー指摘事項
- [x] 入力項目は全て入力必須
- [x] ST2.(2)発生原因は、人的要因=無のときも入力可
- [x] 是正処置-流出作成時、是正処置-発生からのデータコピーは不要
- [x] 検索一覧に不適合SYSの累計滞留日数を追加
- [x] ST2.品証確認欄はST1.インプット情報=QMS不適合の場合は不要
- [x] ステージ追従スクロール
- 担当者変更
- [x] ST1.責任者：部門の役職区分(SL・なし)以外全員
- [x] ST2.作成・点検：部門の役職区分(なし)以外全員
- [x] ST2.作成のデフォルトはST1.責任者
- [x] ST2.品証点検・品証認可はST1の点検・認可と同じ担当者
- [x] ST4.作成点検認可の担当者はST2の作成点検認可と同じ担当者
- [x] ST5.作成点検認可の担当者はST2の作成点検認可と同じ担当者
- [x] ST6.作成点検認可の担当者はST1の作成点検認可と同じ担当者

**Comment by jms-funato** [comment]
### 7/28 指摘事項
- [ ] 入力項目は全て入力必須
- [ ] ST2.(2)発生原因は、人的要因=無のときも入力可
- [ ] 是正処置-流出作成時、是正処置-発生からのデータコピーは不要
- [ ] 検索一覧に不適合SYSの累計滞留日数を追加
- [ ] ST2.品証確認欄はST1.インプット情報=QMS不適合の場合は不要
- 担当者変更
- [ ] ST1.責任者：部門の役職区分(SL・なし)以外全員
- [ ] ST2.作成・点検：部門の役職区分(なし)以外全員
- [ ] ST2.作成のデフォルトはST1.責任者
- [ ] ST2.品証点検・品証認可はST1の点検・認可と同じ担当者
- [ ] ST4.作成点検認可の担当者はST2の作成点検認可と同じ担当者
- [ ] ST5.作成点検認可の担当者はST2の作成点検認可と同じ担当者
- [ ] ST6.作成点検認可の担当者はST1の作成点検認可と同じ担当者

**Comment by jms-funato** [comment]
### 2022/04/20 レビュー　修正事項
- [ ] 画面発生を流出用に転換　流出用は削除
- [ ] インプット情報：製品不適合は非表示　Excelテンプレートも変更
- [ ] ST2：品証確認ステージは不要　ST2認可後はST3処置結果　作成へ
- [ ] ST3：処置結果　ラベルを完了日と結果に分ける
- [ ] ST3以降の点検欄のDatasourceがおかしい（キャプションヒント通りになっているか確認）
- [ ] ST2：作成の担当者　承認担当者マスタを利用　結果的にST3,4の作成者も変更
